/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleHelloWorld;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
//Comentar estas líneas, para el error en Test
//    @Test void someLibraryMethodReturnsTrue() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
//    }
}
